spring.application.name=AgroLink

# Base de datos PostgreSQL - Neon.tech
spring.datasource.url=jdbc:postgresql://ep-square-queen-at4okhg3-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qG9XygfHRB1E
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

# Email
brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${BREVO_FROM_EMAIL}
brevo.from.name=${BREVO_FROM_NAME}

jwt.secret=mi_clave_secreta_super_segura_2024