spring.application.name=AgroLink

#Base de Datos - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/agrolink_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=agrolinkperu2026@gmail.com
spring.mail.password=qtytwtqpkuermvvn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=mi_clave_secreta_super_segura_2024