spring.application.name=AgroLink

# Base de datos PostgreSQL - Neon.tech
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

server.port=${PORT:5000}

# Email
#brevo.api.key=${BREVO_API_KEY}
#brevo.from.email=${BREVO_FROM_EMAIL}
#brevo.from.name=${BREVO_FROM_NAME}

# WhatsApp (Twilio)
#twilio.account.sid=${TWILIO_ACCOUNT_SID}
#twilio.auth.token=${TWILIO_AUTH_TOKEN}
#twilio.whatsapp.from=${TWILIO_WHATSAPP_FROM}

jwt.secret=mi_clave_secreta_super_segura_2024