spring.application.name=AgroLink

# Base de datos PostgreSQL - Neon.tech
spring.datasource.url=jdbc:postgresql://ep-square-queen-at4okhg3-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qG9XygfHRB1E
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

# Email
brevo.api.key=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
brevo.from.email=dayanaracarorojas@gmail.com
brevo.from.name=AgroLink

jwt.secret=mi_clave_secreta_super_segura_2024